package model.enums;

public enum EventType {
    BULLYING_SCANDAL,
    PERSONALITY_CONTROVERSY,
    DATING_SCANDAL,
    SNS_MISTAKE,
    SMOKING,
    PAST_POST_LEAKED,
    ESTATE_PURCHASE,

    DONATION,
    NEW_SONG_RELEASE,
    HEARTWARMING_STORY,
    SCHEDULED_EVENT,
}
