
-- Seed data for posts
INSERT INTO posts (post_id) VALUES ('p_0901');
INSERT INTO posts (post_id) VALUES ('p_0902');
INSERT INTO posts (post_id) VALUES ('p_0903');
INSERT INTO posts (post_id) VALUES ('p_0904');
INSERT INTO posts (post_id) VALUES ('p_0905');
INSERT INTO posts (post_id) VALUES ('p_1001');
INSERT INTO posts (post_id) VALUES ('p_1002');
INSERT INTO posts (post_id) VALUES ('p_1003');
INSERT INTO posts (post_id) VALUES ('p_1004');
INSERT INTO posts (post_id) VALUES ('p_1005');
INSERT INTO posts (post_id) VALUES ('p_1006');
INSERT INTO posts (post_id) VALUES ('p_1007');
INSERT INTO posts (post_id) VALUES ('p_1008');
INSERT INTO posts (post_id) VALUES ('p_1009');
INSERT INTO posts (post_id) VALUES ('p_1010');
INSERT INTO posts (post_id) VALUES ('p_1011');
INSERT INTO posts (post_id) VALUES ('p_1012');
INSERT INTO posts (post_id) VALUES ('p_1013');
INSERT INTO posts (post_id) VALUES ('p_1014');
INSERT INTO posts (post_id) VALUES ('p_1015');
INSERT INTO posts (post_id) VALUES ('p_1016');
INSERT INTO posts (post_id) VALUES ('p_1017');
INSERT INTO posts (post_id) VALUES ('p_1018');
INSERT INTO posts (post_id) VALUES ('p_1019');
INSERT INTO posts (post_id) VALUES ('p_1020');
INSERT INTO posts (post_id) VALUES ('p_1021');
INSERT INTO posts (post_id) VALUES ('p_1022');
INSERT INTO posts (post_id) VALUES ('p_1023');
INSERT INTO posts (post_id) VALUES ('p_1024');
INSERT INTO posts (post_id) VALUES ('p_1025');
INSERT INTO posts (post_id) VALUES ('p_1026');
INSERT INTO posts (post_id) VALUES ('p_1027');
INSERT INTO posts (post_id) VALUES ('p_1028');
INSERT INTO posts (post_id) VALUES ('p_1029');
INSERT INTO posts (post_id) VALUES ('p_1030');
INSERT INTO posts (post_id) VALUES ('m_2001');
INSERT INTO posts (post_id) VALUES ('m_2002');
INSERT INTO posts (post_id) VALUES ('m_2003');
INSERT INTO posts (post_id) VALUES ('m_2004');
INSERT INTO posts (post_id) VALUES ('m_2005');
INSERT INTO posts (post_id) VALUES ('m_2006');
INSERT INTO posts (post_id) VALUES ('m_2007');
INSERT INTO posts (post_id) VALUES ('m_2008');
INSERT INTO posts (post_id) VALUES ('m_2009');
INSERT INTO posts (post_id) VALUES ('m_2010');
INSERT INTO posts (post_id) VALUES ('m_2011');
INSERT INTO posts (post_id) VALUES ('m_2012');
INSERT INTO posts (post_id) VALUES ('m_2013');
INSERT INTO posts (post_id) VALUES ('m_2014');
INSERT INTO posts (post_id) VALUES ('m_2015');
INSERT INTO posts (post_id) VALUES ('m_2016');
INSERT INTO posts (post_id) VALUES ('m_2017');
INSERT INTO posts (post_id) VALUES ('m_2018');
INSERT INTO posts (post_id) VALUES ('m_2019');
INSERT INTO posts (post_id) VALUES ('m_2020');

-- Seed data for comments
INSERT INTO comments (comment_seq, post_id) VALUES (1, 'p_0901');
INSERT INTO comments (comment_seq, post_id) VALUES (1, 'p_0902');
INSERT INTO comments (comment_seq, post_id) VALUES (1, 'p_0903');
INSERT INTO comments (comment_seq, post_id) VALUES (1, 'p_0904');
INSERT INTO comments (comment_seq, post_id) VALUES (1, 'p_0905');
INSERT INTO comments (comment_seq, post_id) VALUES (1, 'p_1001');
INSERT INTO comments (comment_seq, post_id) VALUES (2, 'p_1001');
INSERT INTO comments (comment_seq, post_id) VALUES (1, 'p_1002');
INSERT INTO comments (comment_seq, post_id) VALUES (1, 'p_1003');
INSERT INTO comments (comment_seq, post_id) VALUES (2, 'p_1003');
INSERT INTO comments (comment_seq, post_id) VALUES (3, 'p_1003');
INSERT INTO comments (comment_seq, post_id) VALUES (1, 'p_1004');
INSERT INTO comments (comment_seq, post_id) VALUES (1, 'p_1005');
INSERT INTO comments (comment_seq, post_id) VALUES (1, 'p_1008');
INSERT INTO comments (comment_seq, post_id) VALUES (1, 'p_1010');
INSERT INTO comments (comment_seq, post_id) VALUES (2, 'p_1010');
INSERT INTO comments (comment_seq, post_id) VALUES (1, 'p_1011');
INSERT INTO comments (comment_seq, post_id) VALUES (1, 'p_1012');
INSERT INTO comments (comment_seq, post_id) VALUES (1, 'p_1013');
INSERT INTO comments (comment_seq, post_id) VALUES (1, 'p_1014');
INSERT INTO comments (comment_seq, post_id) VALUES (1, 'p_1016');
INSERT INTO comments (comment_seq, post_id) VALUES (1, 'p_1018');
INSERT INTO comments (comment_seq, post_id) VALUES (2, 'p_1018');
INSERT INTO comments (comment_seq, post_id) VALUES (1, 'p_1020');
INSERT INTO comments (comment_seq, post_id) VALUES (1, 'p_1022');
INSERT INTO comments (comment_seq, post_id) VALUES (1, 'p_1023');
INSERT INTO comments (comment_seq, post_id) VALUES (1, 'p_1024');
INSERT INTO comments (comment_seq, post_id) VALUES (1, 'p_1026');
INSERT INTO comments (comment_seq, post_id) VALUES (1, 'p_1030');